### ISSUE TITLE
Add new Features

### ISSUE THREAD

**Issue by tanwanimohit** [tanwanimohit/twitter-bot#1]
# twitter-bot
A Node JS Based Twitter Bot, which answers your questions.

## Features Currently Supported

- Gives Info About Thing/Place/Person using Duckduckgo API
- Gives you random Quote.
- Gived you random Joke.

## What can you do?
- Add new feature like tell me a whether in Ahmedabad or any useful feature that you can think of.

**Edit : Whether API is Already Integrated by @x4th . think for something else like Current Time API, (Ex. What is the Time in UK etc.)**

## How to Clone?

- Fork the Repo / `git clone https://github.com/tanwanimohit/twitter-bot.git`
- Replace your twitter developer api keys in `config.js`
- Run the app using `node app.js`

**Comment by stefanbajic94** [comment]
I'm currently working on adding a weather request in a specific city using openweathermap's API.
